name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_INSTALL_DIR: ${{ github.workspace }}/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Install .NET 9 SDK
        shell: bash
        run: |
          # Download installation script
          curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x ./dotnet-install.sh

          # Install .NET 9 SDK
          ./dotnet-install.sh --version 9.0.102 --install-dir "$DOTNET_INSTALL_DIR" --verbose

          # Add installation directory to PATH
          echo "$DOTNET_INSTALL_DIR" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$DOTNET_INSTALL_DIR" >> $GITHUB_ENV

      - name: Verify .NET Installation
        shell: bash
        run: |
          echo "Dotnet root: $DOTNET_ROOT"
          echo "PATH: $PATH"
          "$DOTNET_INSTALL_DIR/dotnet" --version
          "$DOTNET_INSTALL_DIR/dotnet" --list-sdks

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-${{ matrix.target }}"

          # Explicitly use the installed .NET 9
          "$DOTNET_INSTALL_DIR/dotnet" publish "./cadmus-tool/cadmus-tool.csproj" \
            --framework net9.0 \
            --self-contained \
            --runtime "${{ matrix.target }}" \
            -c Release \
            -o "$release_name" \
            -v detailed

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
