name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Remove existing .NET installations
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /home/runner/.dotnet

      - name: Install .NET 9 SDK
        shell: bash
        run: |
          # Create new installation directory
          export DOTNET_ROOT=$HOME/.dotnet9
          mkdir -p $DOTNET_ROOT

          # Download and install .NET 9
          curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --version 9.0.102 --install-dir $DOTNET_ROOT

          # Add to PATH with highest priority
          echo "$DOTNET_ROOT" > /tmp/dotnetpath
          echo "$PATH" >> /tmp/dotnetpath
          export PATH=$(paste -d: -s /tmp/dotnetpath)

          # Make variables persist in subsequent steps
          echo "DOTNET_ROOT=$DOTNET_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

          # Verify installation
          echo "Installed SDK version:"
          $DOTNET_ROOT/dotnet --version
          $DOTNET_ROOT/dotnet --list-sdks

      - name: Build
        shell: bash
        run: |
          # Ensure we're using the correct dotnet
          echo "Using dotnet from: $(which dotnet)"
          echo "Dotnet version: $(dotnet --version)"

          tag=$(git describe --tags --abbrev=0)
          release_name="App-$tag-${{ matrix.target }}"

          # Build everything with explicit SDK path
          $DOTNET_ROOT/dotnet publish "./cadmus-tool/cadmus-tool.csproj" --framework net9.0 --self-contained --runtime "${{ matrix.target }}" -c Release -o "$release_name"

          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
